package pl.prodevcode.learnmobiledev.core.ui

/**
 * Every user-facing string in the app, identified by a stable key.
 *
 * ### Why not Compose Resources?
 * `Res.string` resolves `values-pl/` from the **system** locale, and in Compose
 * Multiplatform 1.11 that cannot be overridden: `ResourceEnvironment` has an internal
 * constructor and `LocalComposeEnvironment` is internal. An in-app language switch would
 * therefore change the course content but leave tab labels and buttons in the system
 * language.
 *
 * Loading the catalogue ourselves fixes that and, as a bonus, leaves the project with a
 * single localization mechanism for both UI strings and course content.
 *
 * The enum keeps keys type-safe: a typo is a compile error, and an unused entry is
 * visible to the IDE.
 */
enum class AppString(val key: String) {
    ActionBack("action_back"),
    ActionCancel("action_cancel"),
    ActionClear("action_clear"),
    ActionDone("action_done"),
    ActionHide("action_hide"),
    ActionReset("action_reset"),
    ActionRetry("action_retry"),
    ActionSave("action_save"),
    AppName("app_name"),
    CategoryAndroid("category_android"),
    CategoryClean("category_clean"),
    CategoryCompose("category_compose"),
    CategoryCoroutines("category_coroutines"),
    CategoryDataStructures("category_data_structures"),
    CategoryKmp("category_kmp"),
    CategoryKotlin("category_kotlin"),
    CategoryMvi("category_mvi"),
    CategoryPerformance("category_performance"),
    CategoryRx("category_rx"),
    CategorySolid("category_solid"),
    CategoryTesting("category_testing"),
    DifficultyMid("difficulty_mid"),
    DifficultySenior("difficulty_senior"),
    ErrorFavoriteRejected("error_favorite_rejected"),
    ErrorGeneric("error_generic"),
    ErrorLessonsUnavailable("error_lessons_unavailable"),
    ErrorNetworkUnavailable("error_network_unavailable"),
    ErrorQuestionsUnavailable("error_questions_unavailable"),
    ErrorRollbackSuffix("error_rollback_suffix"),
    ErrorScenarioFailed("error_scenario_failed"),
    ErrorScenariosUnavailable("error_scenarios_unavailable"),
    ErrorUnknown("error_unknown"),
    ErrorUserInvalid("error_user_invalid"),
    ErrorUserNotFound("error_user_not_found"),
    LanguageEnglish("language_english"),
    LanguageNameEnglish("language_name_english"),
    LanguageNamePolish("language_name_polish"),
    LanguagePickerDescription("language_picker_description"),
    LanguagePickerTitle("language_picker_title"),
    LanguagePolish("language_polish"),
    LanguageRestartHint("language_restart_hint"),
    LearnDoneBadge("learn_done_badge"),
    LearnExercisePrefix("learn_exercise_prefix"),
    LearnMarkDone("learn_mark_done"),
    LearnMarkedDone("learn_marked_done"),
    LearnProgress("learn_progress"),
    LearnSubtitle("learn_subtitle"),
    LearnTitle("learn_title"),
    MarkerBug("marker_bug"),
    MarkerBullet("marker_bullet"),
    MarkerCorrect("marker_correct"),
    MarkerIncorrect("marker_incorrect"),
    MarkerLogLine("marker_log_line"),
    MarkerNone("marker_none"),
    MarkerOption("marker_option"),
    MarkerRule("marker_rule"),
    QuizAllCategories("quiz_all_categories"),
    QuizBackToCategories("quiz_back_to_categories"),
    QuizBackToList("quiz_back_to_list"),
    QuizClearFilter("quiz_clear_filter"),
    QuizCorrect("quiz_correct"),
    QuizCorrectAnswer("quiz_correct_answer"),
    QuizCorrectCount("quiz_correct_count"),
    QuizCorrectLabel("quiz_correct_label"),
    QuizExerciseLabel("quiz_exercise_label"),
    QuizExitConfirm("quiz_exit_confirm"),
    QuizExitDismiss("quiz_exit_dismiss"),
    QuizExitMessageProgress("quiz_exit_message_progress"),
    QuizExitMessageSingle("quiz_exit_message_single"),
    QuizExitTitle("quiz_exit_title"),
    QuizFinish("quiz_finish"),
    QuizLoadError("quiz_load_error"),
    QuizMeta("quiz_meta"),
    QuizMistakesTitle("quiz_mistakes_title"),
    QuizNewTest("quiz_new_test"),
    QuizNext("quiz_next"),
    QuizNoMistakes("quiz_no_mistakes"),
    QuizNoQuestions("quiz_no_questions"),
    QuizPickCategories("quiz_pick_categories"),
    QuizProgress("quiz_progress"),
    QuizRetryMistakes("quiz_retry_mistakes"),
    QuizScore("quiz_score"),
    QuizScorePercent("quiz_score_percent"),
    QuizSelectedCount("quiz_selected_count"),
    QuizStart("quiz_start"),
    QuizSubtitle("quiz_subtitle"),
    QuizTitle("quiz_title"),
    QuizVerdictAverage("quiz_verdict_average"),
    QuizVerdictExcellent("quiz_verdict_excellent"),
    QuizVerdictGood("quiz_verdict_good"),
    QuizVerdictWeak("quiz_verdict_weak"),
    QuizWrong("quiz_wrong"),
    SyncActual("sync_actual"),
    SyncExpectation("sync_expectation"),
    SyncExpected("sync_expected"),
    SyncExplain("sync_explain"),
    SyncFailureHint("sync_failure_hint"),
    SyncHideExplanation("sync_hide_explanation"),
    SyncPassedSummary("sync_passed_summary"),
    SyncRun("sync_run"),
    SyncRunAll("sync_run_all"),
    SyncRunInProgress("sync_run_in_progress"),
    SyncRunning("sync_running"),
    SyncStatusFail("sync_status_fail"),
    SyncStatusPass("sync_status_pass"),
    SyncSubtitle("sync_subtitle"),
    SyncTitle("sync_title"),
    TabDemo("tab_demo"),
    TabDemoIcon("tab_demo_icon"),
    TabLearn("tab_learn"),
    TabLearnIcon("tab_learn_icon"),
    TabSync("tab_sync"),
    TabSyncIcon("tab_sync_icon"),
    TabTest("tab_test"),
    TabTestIcon("tab_test_icon"),
    ThemeDark("theme_dark"),
    ThemeLight("theme_light"),
    ThemeToggleDescription("theme_toggle_description"),
    UserDetailsEdit("user_details_edit"),
    UserDetailsFavorite("user_details_favorite"),
    UserDetailsNotFavorite("user_details_not_favorite"),
    UserDetailsNotFound("user_details_not_found"),
    UserEditEmail("user_edit_email"),
    UserEditName("user_edit_name"),
    UserEditRole("user_edit_role"),
    UserEditSaved("user_edit_saved"),
    UserEditSaving("user_edit_saving"),
    UserEditTitle("user_edit_title"),
    UsersEmpty("users_empty"),
    UsersEmptyQuery("users_empty_query"),
    UsersFavoriteNo("users_favorite_no"),
    UsersFavoriteSaving("users_favorite_saving"),
    UsersFavoriteYes("users_favorite_yes"),
    UsersFavoritesSummary("users_favorites_summary"),
    UsersRefresh("users_refresh"),
    UsersRefreshing("users_refreshing"),
    UsersSearchLabel("users_search_label"),
    UsersSimulateError("users_simulate_error"),
    UsersTimelineCollapse("users_timeline_collapse"),
    UsersTimelineEntry("users_timeline_entry"),
    UsersTimelineExpand("users_timeline_expand"),
    UsersTimelineInitial("users_timeline_initial"),
    UsersTimelineTitle("users_timeline_title"),
    UsersTitle("users_title"),
    ;

    companion object {
        val BY_KEY: Map<String, AppString> = entries.associateBy { it.key }
    }
}
